//! Conversion from layer 1 (the private `schema` module, generated by
//! xsd-parser from the SUMO XSDs) to layer 2
//! ([`crate::additional::domain`]).
//!
//! Mirrors the other formats' mappers in spirit, but is independent code:
//! `additional` doesn't require `net` or `routes` to be enabled, so it
//! can't reuse their conversions.
//!
//! The one thing worth knowing here is that SUMO's `floatType` is declared
//! in `types/base.xsd` as an `xsd:string` restricted by a pattern, not as
//! `xsd:float` — so xsd-parser hands positions over as `String` and this
//! module parses them. `positiveFloatType` and `nonNegativeFloatType` *are*
//! real `xsd:float`s, and arrive as `f32`.

use super::domain::{
    Additional, DetectorGate, DetectorId, E1Detector, E2Detector, E3Detector, LanePosition, LaneRef,
};
use crate::schema;
use anyhow::{Context, Result, bail};
use uom::si::f64::{Length, Time, Velocity};
use uom::si::length::meter;
use uom::si::time::second;
use uom::si::velocity::meter_per_second;

/// Parses one of SUMO's text-encoded `floatType` values, rejecting `NaN`
/// and the infinities for the same reason `net`'s mapper does: `f64`'s
/// `FromStr` accepts them, SUMO's pattern doesn't, and xsd-parser enforces
/// no `xsd:pattern`.
fn parse_finite(raw: &str, context: &str) -> Result<f64> {
    let value: f64 = raw
        .trim()
        .parse()
        .with_context(|| format!("invalid {context}: {raw:?}"))?;

    if !value.is_finite() {
        bail!("non-finite {context}: {raw:?}");
    }

    Ok(value)
}

fn lane_position(raw: &str, context: &str) -> Result<LanePosition> {
    Ok(LanePosition(Length::new::<meter>(parse_finite(
        raw, context,
    )?)))
}

/// `lanes` is a whitespace-separated list of lane ids, same convention as
/// the other formats' id lists.
fn split_lane_refs(raw: &str) -> Vec<LaneRef> {
    raw.split_whitespace()
        .map(|id| LaneRef(id.to_owned()))
        .collect()
}

fn seconds(value: Option<f32>) -> Option<Time> {
    value.map(|s| Time::new::<second>(f64::from(s)))
}

fn meters(value: Option<f32>) -> Option<Length> {
    value.map(|m| Length::new::<meter>(f64::from(m)))
}

/// SUMO's `period` supersedes the deprecated `freq`; both mean the same
/// sampling interval, so fall back to `freq` when only it is present.
fn sampling_period(period: Option<f32>, freq: Option<f32>) -> Option<Time> {
    seconds(period.or(freq))
}

/// `bool` conversion goes through the same `schema::BoolType` table `net`
/// uses, but that impl lives behind the `net` feature, so it is repeated
/// here rather than depended on.
fn optional_bool(value: Option<schema::BoolType>) -> Result<Option<bool>> {
    use schema::BoolType as S;

    value
        .map(|value| match value {
            S::true_ | S::True | S::yes | S::on | S::_1 => Ok(true),
            S::false_ | S::False | S::no | S::off | S::_0 => Ok(false),
            S::x | S::Dash => {
                bail!("SUMO boolean value with no binary meaning (\"x\"/\"-\")")
            }
        })
        .transpose()
}

impl TryFrom<schema::DetEntryExitType> for DetectorGate {
    type Error = anyhow::Error;

    fn try_from(value: schema::DetEntryExitType) -> Result<Self> {
        Ok(DetectorGate {
            lane: LaneRef(value.lane),
            position: lane_position(&value.pos, "detector gate position")?,
            friendly_position: optional_bool(value.friendly_pos)?,
        })
    }
}

impl TryFrom<schema::E1DetectorType> for E1Detector {
    type Error = anyhow::Error;

    fn try_from(value: schema::E1DetectorType) -> Result<Self> {
        Ok(E1Detector {
            id: DetectorId(value.id),
            lane: LaneRef(value.lane),
            position: lane_position(&value.pos, "e1Detector position")?,
            file: value.file,
            period: sampling_period(value.period, value.freq),
            length: meters(value.length),
            name: value.name,
            friendly_position: optional_bool(value.friendly_pos)?,
        })
    }
}

impl TryFrom<schema::E2DetectorType> for E2Detector {
    type Error = anyhow::Error;

    fn try_from(value: schema::E2DetectorType) -> Result<Self> {
        Ok(E2Detector {
            id: DetectorId(value.id),
            lane: value.lane.map(LaneRef),
            lanes: value
                .lanes
                .as_deref()
                .map(split_lane_refs)
                .unwrap_or_default(),
            position: value
                .pos
                .as_deref()
                .map(|pos| lane_position(pos, "e2Detector position"))
                .transpose()?,
            end_position: value
                .end_pos
                .as_deref()
                .map(|pos| lane_position(pos, "e2Detector end position"))
                .transpose()?,
            length: value
                .length
                .as_deref()
                .map(|raw| parse_finite(raw, "e2Detector length"))
                .transpose()?
                .map(Length::new::<meter>),
            file: value.file,
            period: sampling_period(value.period, value.freq),
            name: value.name,
            friendly_position: optional_bool(value.friendly_pos)?,
            speed_threshold: value
                .speed_threshold
                .as_deref()
                .map(|raw| parse_finite(raw, "e2Detector speed threshold"))
                .transpose()?
                .map(Velocity::new::<meter_per_second>),
        })
    }
}

impl TryFrom<schema::E3DetectorType> for E3Detector {
    type Error = anyhow::Error;

    fn try_from(value: schema::E3DetectorType) -> Result<Self> {
        let mut entries = Vec::new();
        let mut exits = Vec::new();

        for item in value.content.det_gate_group {
            match item.content {
                schema::E3DetectorDetGateGroupTypeContent::detEntry(gates) => {
                    for gate in gates {
                        entries.push(DetectorGate::try_from(gate)?);
                    }
                }
                schema::E3DetectorDetGateGroupTypeContent::detExit(gates) => {
                    for gate in gates {
                        exits.push(DetectorGate::try_from(gate)?);
                    }
                }
            }
        }

        Ok(E3Detector {
            id: DetectorId(value.id),
            entries,
            exits,
            file: value.file,
            period: sampling_period(value.period, value.freq),
            name: value.name,
            icon_position: value.pos,
            speed_threshold: value
                .speed_threshold
                .map(|s| Velocity::new::<meter_per_second>(f64::from(s))),
            open_entry: optional_bool(value.open_entry)?,
        })
    }
}

impl TryFrom<schema::AdditionalType> for Additional {
    type Error = anyhow::Error;

    fn try_from(value: schema::AdditionalType) -> Result<Self> {
        let mut additional = Additional::default();

        for item in value.content {
            match item {
                // `inductionLoop`, `laneAreaDetector` and `entryExitDetector`
                // are SUMO's alternative spellings of `e1Detector`,
                // `e2Detector` and `e3Detector`: the same XSD type under a
                // second element name, so both map to the same domain type.
                schema::AdditionalTypeContent::e1Detector(Some(detector))
                | schema::AdditionalTypeContent::inductionLoop(Some(detector)) => {
                    additional
                        .induction_loops
                        .push(E1Detector::try_from(detector)?);
                }
                schema::AdditionalTypeContent::e2Detector(Some(detector))
                | schema::AdditionalTypeContent::laneAreaDetector(Some(detector)) => {
                    additional
                        .lane_area_detectors
                        .push(E2Detector::try_from(detector)?);
                }
                schema::AdditionalTypeContent::e3Detector(Some(detector))
                | schema::AdditionalTypeContent::entryExitDetector(Some(detector)) => {
                    additional
                        .entry_exit_detectors
                        .push(E3Detector::try_from(detector)?);
                }
                // Every other `additionalType` element kind (`busStop`,
                // `rerouter`, `calibrator`, `parkingArea`, `poly`, the whole
                // of `routesType` again, ...), and any of the above that
                // showed up as `None` (shouldn't happen per the XSD, but
                // xsd-parser models each choice branch as optional) — not
                // modelled, see the `domain` module docs.
                _ => {}
            }
        }

        Ok(additional)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_non_finite_gate_position() {
        assert!(lane_position("NaN", "test").is_err());
        assert!(lane_position("inf", "test").is_err());
        assert!(lane_position("not-a-number", "test").is_err());
    }

    #[test]
    fn parses_a_negative_position_as_given() {
        // SUMO reads a negative `pos` as "measured back from the lane's
        // end". Resolving it needs the lane's length, which lives in the
        // `.net.xml`, so it is kept verbatim rather than normalised.
        let position = lane_position("-12.5", "test").unwrap();
        assert_eq!(position.0.get::<meter>(), -12.5);
    }

    #[test]
    fn falls_back_from_period_to_the_deprecated_freq() {
        use uom::si::time::second;

        assert_eq!(
            sampling_period(Some(60.0), None).unwrap().get::<second>(),
            60.0
        );
        assert_eq!(
            sampling_period(None, Some(30.0)).unwrap().get::<second>(),
            30.0
        );
        // `period` wins when SUMO wrote both.
        assert_eq!(
            sampling_period(Some(60.0), Some(30.0))
                .unwrap()
                .get::<second>(),
            60.0
        );
        assert!(sampling_period(None, None).is_none());
    }

    #[test]
    fn splits_a_lane_chain() {
        assert_eq!(
            split_lane_refs("e0_0 e1_0  e2_0"),
            vec![
                LaneRef("e0_0".into()),
                LaneRef("e1_0".into()),
                LaneRef("e2_0".into())
            ]
        );
    }

    #[test]
    fn rejects_bool_without_binary_meaning() {
        assert!(optional_bool(Some(schema::BoolType::x)).is_err());
        assert_eq!(optional_bool(None).unwrap(), None);
        assert_eq!(
            optional_bool(Some(schema::BoolType::True)).unwrap(),
            Some(true)
        );
    }
}
